# Generated by Django 3.2.16 on 2023-01-03 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='class',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='class',
            name='post',
        ),
        migrations.AddField(
            model_name='announcement',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.class'),
        ),
        migrations.AddField(
            model_name='post',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.class'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
