# Generated by Django 2.2 on 2023-01-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='etl.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly', to='etl.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='modules/')),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_content', to='etl.Weekly')),
            ],
        ),
    ]
