# Generated by Django 3.2.16 on 2023-01-03 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0002_auto_20230103_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
