# Generated by Django 2.2 on 2023-01-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_post_hits'),
    ]

    operations = [
    ]
