# Generated by Django 2.2 on 2023-01-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_post_hits'),
        ('etl', '0003_alter_assignment_id_alter_assignmenttostudent_id_and_more'),
    ]

    operations = [
    ]
