# Generated by Django 4.1.5 on 2023-01-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_rename_author_post_created_by_assignment_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='professor',
            new_name='created_by',
        ),
    ]
