# Generated by Django 4.1.5 on 2023-01-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_rename_professor_class_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='created_by',
        ),
    ]
