# Generated by Django 4.1.5 on 2023-01-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_alter_comment_created_at_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='assignmenttostudent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
