# Generated by Django 3.2.16 on 2023-01-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_qualified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_qualified',
        ),
    ]
